[package]
name = "space-search"
version = "5.0.0"
edition = "2021"
description = "A library providing basic generic depth-first, breadth-first, heuristic-guided, and A* search space exploration algorithms."
license = "MIT"

[dependencies]
num = "0.4.3"
