[package]
name = "space-search"
version = "2.0.0"
edition = "2021"
description = "A library providing basic utilities for performing generic depth-first, breadth-first, and heuristic-guided search space exploration algorithms."
license = "MIT"

[dependencies]
